### ISSUE TITLE
WQhat causes this?

### ISSUE THREAD

**Issue by GypsyVanMan** [linuxserver/docker-mylar3#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to click on 'this week' tap

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 2764, in pullist
    repoll = self.pullrecreate(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 2987, in pullrecreate
    statchk = weeklypull.pullit(forcecheck, weeknumber, year)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/weeklypull.py", line 115, in pullit
    new_pullcheck(chk_locg['weeknumber'],chk_locg['year'])
  File "/app/mylar3/mylar/weeklypull.py", line 934, in new_pullcheck
    if 'Present' in watch['ComicPublished'] or (helpers.now()[:4] in watch['ComicPublished']) or watch['ForceContinuing'] == 1 or len(listit) >0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

Powered by [CherryPy 18.8.0](http://www.cherrypy.dev/)

### Expected Behavior

Should show pull list

### Steps To Reproduce

restart and ckick on tab

### Environment

```markdown
- OS: Unraid
- How docker service was installed:Community app
```

### CPU architecture

x86-64

### Docker creation

```bash
???
```

### Container logs

```bash
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 2764, in pullist
    repoll = self.pullrecreate(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 2987, in pullrecreate
    statchk = weeklypull.pullit(forcecheck, weeknumber, year)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/weeklypull.py", line 115, in pullit
    new_pullcheck(chk_locg['weeknumber'],chk_locg['year'])
  File "/app/mylar3/mylar/weeklypull.py", line 934, in new_pullcheck
    if 'Present' in watch['ComicPublished'] or (helpers.now()[:4] in watch['ComicPublished']) or watch['ForceContinuing'] == 1 or len(listit) >0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

Powered by CherryPy 18.8.0
```

**Comment by aptalca** [comment]
That looks like a mylar3 issue rather than a container one
