### ISSUE TITLE
[BUG] <title>Errno 13 trying to add new comics

### ISSUE THREAD

**Issue by ysarkain** [linuxserver/docker-mylar3#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to add a new comic I am getting a permission error which causes the add/refresh to just spin forever:

```
23-Dec-2023 16:31:36 - INFO :: mylar.getImage.4143 : mass-refresh : Attempting to retrieve the comic image for series
23-Dec-2023 16:31:37 - ERROR :: mylar.excepthook.315 : mass-refresh : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/importer.py", line 326, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/helpers.py", line 4161, in getImage
    with open(coverfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/mylar/cache/30585.jpg'

Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/importer.py", line 326, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/helpers.py", line 4161, in getImage
    with open(coverfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/mylar/cache/30585.jpg'
```

This was working fine until the last update of latest.  I tried updating to nightly and I still get the issue.

I am running unraid, using the docker container from the community apps.  It has been working fine for months, this behavior only started in the last couple days, I believe it updated a couple days ago.

I have had permission issues before since I was copying files through a samba share, but I fixed that issue by using force user=nobody on the share and now all files are coming through as owned by nobody:users, and in the container they show as abc:abc.

Permissions from Unraid shell:
```
└[/mnt/user/appdata/mylar3/mylar/cache]> ll 30*.jpg
-rw-rw-rw- 1 nobody users 135K Nov 15 15:01 30450.jpg
-rw-rw-rw- 1 nobody users 119K Dec  3 21:03 30462.jpg
-rw-rw-rw- 1 nobody users 137K Dec 13 10:41 30465.jpg
-rw-rw-rw- 1 nobody users  45K Dec 10 15:39 30472.jpg
-rw-rw-rw- 1 nobody users  34K Nov 14 10:11 30475.jpg
-rw-rw-rw- 1 nobody users 150K Nov 14 09:23 30496.jpg
-rw-rw-rw- 1 nobody users 184K Dec 14 09:28 30574.jpg
-rw-rw-rw- 1 nobody users  40K Dec 14 09:47 30596.jpg
-rw-rw-rw- 1 nobody users 144K Dec 21 18:05 30597.jpg
-rw-rw-rw- 1 nobody users  31K Oct 16 22:44 30783.jpg
-rw-rw-rw- 1 nobody users  41K Oct 16 22:52 30785.jpg
-rw-rw-rw- 1 nobody users  56K Oct 15 21:24 3086.jpg
-rw-rw-rw- 1 nobody users  68K Oct 16 00:36 30954.jpg
```

Permissions from mylar3 console:
```
root@81d4867d4b41:/config/mylar/cache# ls -l 30*
-rw-rw-rw- 1 abc abc 137818 Nov 15 15:01 30450.jpg
-rw-rw-rw- 1 abc abc 120837 Dec  3 21:03 30462.jpg
-rw-rw-rw- 1 abc abc 139666 Dec 13 10:41 30465.jpg
-rw-rw-rw- 1 abc abc  45597 Dec 10 15:39 30472.jpg
-rw-rw-rw- 1 abc abc  34002 Nov 14 10:11 30475.jpg
-rw-rw-rw- 1 abc abc 152825 Nov 14 09:23 30496.jpg
-rw-rw-rw- 1 abc abc 188319 Dec 14 09:28 30574.jpg
-rw-rw-rw- 1 abc abc  40202 Dec 14 09:47 30596.jpg
-rw-rw-rw- 1 abc abc 146782 Dec 21 18:05 30597.jpg
-rw-rw-rw- 1 abc abc  31575 Oct 16 22:44 30783.jpg
-rw-rw-rw- 1 abc abc  41364 Oct 16 22:52 30785.jpg
-rw-rw-rw- 1 abc abc  57332 Oct 15 21:24 3086.jpg
-rw-rw-rw- 1 abc abc  69060 Oct 16 00:36 30954.jpg
```

The files are clearly owned by the mylar user and are set 666 so I don't know how there can be a permission issue.

Screenshot of comic screen after attempt:
![2023-12-23 16_44_34-Clipboard](https://github.com/linuxserver/docker-mylar3/assets/14844795/26e3dd16-7229-459d-91f5-f17cbdd1ce11)

### Expected Behavior

It should add the comic and store a cover image in the cache directory.

### Steps To Reproduce

1. Install mylar3 docker container in unraid
2. Attempt to add a new comic title

### Environment

```markdown
- OS: Unraid 6.12.4
- How docker service was installed: Unraid default
```

### CPU architecture

x86-64

### Docker creation

```bash
https://imgur.com/aB3Wv5y
```

### Container logs

```bash
└[/mnt/user/appdata/mylar3/mylar/cache]> docker logs mylar3
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Mylar3: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EWQADB5AMVRFU

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1122 : MainThread : [DOCKER-AWARE] Docker installation detected.
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1188 : MainThread : Ignored Publishers: []
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1211 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1223 : MainThread : [IGNORE_SEARCH_WORDS] Words to flag search result as invalid: ['.exe', '.iso', 'pdf-xpost', 'pdf', 'ebook']
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1235 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1249 : MainThread : [COMICTAGGER] Version detected: 1.3.5
23-Dec-2023 16:25:37 - INFO :: mylar.configure.1342 : MainThread : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
23-Dec-2023 16:25:37 - INFO :: mylar.initialize.259 : MainThread : Checking to see if the database has all tables....
23-Dec-2023 16:25:37 - INFO :: mylar.dbcheck.1562 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
23-Dec-2023 16:25:37 - INFO :: mylar.dbcheck.1572 : MainThread : Correcting Null entries that make the main page break on startup.
23-Dec-2023 16:25:37 - INFO :: mylar.dbcheck.1583 : MainThread : [<class 'int'>]oldconfig_version: 12
23-Dec-2023 16:25:37 - INFO :: mylar.check_failed_update.172 : MainThread : checked is None
23-Dec-2023 16:25:37 - INFO :: mylar.initialize.288 : MainThread : Successfully discovered local IP and locking it in as : 172.17.0.14
23-Dec-2023 16:25:37 - INFO :: mylar.initialize.369 : MainThread : [IMPRINT_LOADS] No data for publisher imprints locally. Retrieving up-to-date listing
23-Dec-2023 16:25:37 - ERROR :: mylar.initialize.378 : MainThread : Unable to write imprints.json to /config/mylar/cache/imprints.json. Error returned: [Errno 13] Permission denied: '/config/mylar/cache/imprints.json'
23-Dec-2023 16:25:37 - INFO :: mylar.initialize.393 : MainThread : Remapping the sorting to allow for new additions.
23-Dec-2023 16:25:37 - INFO :: mylar.ComicSort.779 : MainThread : Sucessfully ordered 903 series in your watchlist.
23-Dec-2023 16:27:45 - WARNING :: mylar.SABtest.7207 : MainThread : Error fetching data from http://192.168.1.175:8080/api: HTTPConnectionPool(host='192.168.1.175', port=8080): Max retries exceeded with url: /api?mode=version (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x14b782dae5d0>, 'Connection to 192.168.1.175 timed out. (connect timeout=None)'))
23-Dec-2023 16:27:45 - WARNING :: mylar.SABtest.7209 : MainThread : Cannot verify ssl certificate. Attempting to authenticate with no ssl-certificate verification.
23-Dec-2023 16:29:56 - WARNING :: mylar.SABtest.7225 : MainThread : Error fetching data from http://192.168.1.175:8080/: HTTPConnectionPool(host='192.168.1.175', port=8080): Max retries exceeded with url: /api?mode=version (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x14b781f9d890>, 'Connection to 192.168.1.175 timed out. (connect timeout=None)'))
23-Dec-2023 16:29:56 - INFO :: mylar.initialize.403 : MainThread : [SAB-VERSION-CHECK] SABnzbd version detected as: 4.1.0
23-Dec-2023 16:29:56 - INFO :: mylar.validateAndCreateDirectory.1857 : MainThread : [DIRECTORY-CHECK] Found DATA directory: /config/mylar
23-Dec-2023 16:29:56 - INFO :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/
23-Dec-2023 16:29:56 - INFO :: mylar.getVersion.188 : MAIN : [DOCKER-AWARE] Docker installation detected.
23-Dec-2023 16:29:56 - INFO :: mylar.getVersion.209 : MAIN : i:  (python3-dev)

23-Dec-2023 16:29:56 - INFO :: mylar.getVersion.228 : MAIN : [LAST_RELEASE] Branch: python3-dev
23-Dec-2023 16:29:56 - INFO :: mylar.getVersion.209 : MAIN : i: f570294d08e6cf2e770d62dde9300ee4bc5565d5

23-Dec-2023 16:29:56 - INFO :: mylar.getVersion.231 : MAIN : [LAST_RELEASE] Commit: f570294d08e6cf2e770d62dde9300ee4bc5565d5
23-Dec-2023 16:29:56 - INFO :: mylar.getVersion.266 : MAIN : Branch detected & set to : python3-dev
23-Dec-2023 16:29:56 - INFO :: mylar.versionload.469 : MAIN : Version information: python3-dev [f570294d08e6cf2e770d62dde9300ee4bc5565d5]
[ls.io-init] done.
23-Dec-2023 16:29:57 - INFO :: mylar.release_messages.274 : MAIN : release_messages: None
23-Dec-2023 16:29:57 - INFO :: mylar.start.669 : MAIN : [SEARCH-QUEUE] Attempting to background load the search queue....
23-Dec-2023 16:29:57 - INFO :: mylar.start.673 : MAIN : [SEARCH-QUEUE] Successfully started the Search Queuer...
23-Dec-2023 16:29:57 - INFO :: mylar.queue_schedule.712 : MAIN : [SAB-MONITOR] Completed post-processing handling enabled for SABnzbd. Attempting to background load....
23-Dec-2023 16:29:57 - INFO :: mylar.queue_schedule.718 : MAIN : [AUTO-COMPLETE-NZB] Succesfully started Completed post-processing handling for SABnzbd - will now monitor for completed nzbs within sabnzbd and post-process automatically...
23-Dec-2023 16:29:57 - INFO :: mylar.start.669 : MAIN : [POST-PROCESS-QUEUE] Post Process queue enabled & monitoring for api requests....
23-Dec-2023 16:29:57 - INFO :: mylar.start.673 : MAIN : [POST-PROCESS-QUEUE] Succesfully started Post-Processing Queuer....
23-Dec-2023 16:29:57 - INFO :: mylar.latestdate_fix.1330 : MAIN : Preparing to correct/fix 1 series that have incorrect values given for the Latest Date field.
23-Dec-2023 16:29:58 - INFO :: mylar.latestdate_fix.1336 : MAIN : Preparing to update 1 series on your watchlist for use with non-ascii characters
23-Dec-2023 16:29:58 - INFO :: mylar.start.588 : MAIN : [WEEKLY] Checking for existance of Weekly Comic listing...
23-Dec-2023 16:29:58 - INFO :: mylar.start.647 : MAIN : Firing up the Background Schedulers now....
23-Dec-2023 16:29:58 - INFO :: mylar.start.652 : MAIN : Background Schedulers successfully started...
23-Dec-2023 16:30:08 - WARNING :: mylar.havetotals.1529 : CP Server Thread-6 : [Error: expected string or bytes-like object, got 'NoneType'] No Publisher found for Tex Morgan - you probably want to Refresh the series when you get a chance.
23-Dec-2023 16:30:19 - ERROR :: mylar.get_imprint_volume_and_booktype.1247 : CP Server Thread-2 : error: 'NoneType' object has no attribute 'items'
23-Dec-2023 16:30:19 - INFO :: mylar.get_imprint_volume_and_booktype.1417 : CP Server Thread-2 : comic_values: {'ComicYear': '1948', 'ComicPublisher': 'Marvel', 'PublisherImprint': None, 'ComicDescription': 'Tex Morgan ran during 1948 through 1950 for 9 issues. ', 'ComicVersion': 'None', 'Type': 'Print', 'incorrect_volume': None}
23-Dec-2023 16:30:19 - INFO :: mylar.loadSearchResults.969 : CP Server Thread-5 : # of results: 1
23-Dec-2023 16:30:20 - INFO :: mylar.scale_image.75 : CP Server Thread-6 : converted to webp...
23-Dec-2023 16:30:40 - INFO :: mylar.refreshSeries.1919 : CP Server Thread-6 : [SHIZZLE-WHIZZLE] Now queueing to refresh Tex Morgan (1948)
23-Dec-2023 16:30:40 - INFO :: mylar.refresh_thread.1931 : CP Server Thread-6 : [MASS-REFRESH] MASS_REFRESH thread not started. Started & submitting.
23-Dec-2023 16:30:43 - INFO :: mylar.addvialist.51 : mass-refresh : [MASS-REFRESH][1/1] Now refreshing Tex Morgan (1948) [30585] 
23-Dec-2023 16:30:43 - INFO :: mylar.dbUpdate.150 : mass-refresh : Refreshing/Updating: Tex Morgan (1948) [30585]
23-Dec-2023 16:30:43 - INFO :: mylar.addComictoDB.100 : mass-refresh : aliases currently: None
23-Dec-2023 16:30:43 - INFO :: mylar.validateAndCreateDirectory.1857 : mass-refresh : [DIRECTORY-CHECK] Found comic directory: /comics/Timely Comics/Tex Morgan (Timely, 1948-1950)
23-Dec-2023 16:30:45 - INFO :: mylar.scale_image.75 : CP Server Thread-10 : converted to webp...
23-Dec-2023 16:30:45 - ERROR :: mylar.get_imprint_volume_and_booktype.1247 : mass-refresh : error: 'NoneType' object has no attribute 'items'
23-Dec-2023 16:30:45 - INFO :: mylar.get_imprint_volume_and_booktype.1417 : mass-refresh : comic_values: {'ComicYear': '1948', 'ComicPublisher': 'Marvel', 'PublisherImprint': None, 'ComicDescription': 'Tex Morgan ran during 1948 through 1950 for 9 issues. ', 'ComicVersion': 'None', 'Type': 'Print', 'incorrect_volume': None}
23-Dec-2023 16:30:45 - INFO :: mylar.addComictoDB.166 : mass-refresh : Now adding/updating: Tex Morgan
23-Dec-2023 16:30:45 - INFO :: mylar.addComictoDB.223 : mass-refresh : Sucessfully retrieved details for Tex Morgan
23-Dec-2023 16:30:45 - INFO :: mylar.addComictoDB.234 : mass-refresh : Previous version detected as None - seeing if update required
23-Dec-2023 16:30:45 - INFO :: mylar.addComictoDB.298 : mass-refresh : Directory (/comics/Timely Comics/Tex Morgan (Timely, 1948-1950)) already exists! Continuing...
23-Dec-2023 16:30:47 - INFO :: mylar.getImage.4143 : mass-refresh : Attempting to retrieve the comic image for series
23-Dec-2023 16:30:47 - ERROR :: mylar.excepthook.315 : mass-refresh : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/importer.py", line 326, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/helpers.py", line 4161, in getImage
    with open(coverfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/mylar/cache/30585.jpg'

Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/importer.py", line 326, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/helpers.py", line 4161, in getImage
    with open(coverfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/mylar/cache/30585.jpg'
23-Dec-2023 16:31:29 - INFO :: mylar.refreshSeries.1919 : CP Server Thread-8 : [SHIZZLE-WHIZZLE] Now queueing to refresh Tex Morgan (1948)
23-Dec-2023 16:31:29 - INFO :: mylar.refresh_thread.1931 : CP Server Thread-8 : [MASS-REFRESH] MASS_REFRESH thread not started. Started & submitting.
23-Dec-2023 16:31:32 - INFO :: mylar.addvialist.51 : mass-refresh : [MASS-REFRESH][1/1] Now refreshing Tex Morgan (1948) [30585] 
23-Dec-2023 16:31:32 - INFO :: mylar.dbUpdate.150 : mass-refresh : Refreshing/Updating: Tex Morgan (1948) [30585]
23-Dec-2023 16:31:32 - INFO :: mylar.addComictoDB.100 : mass-refresh : aliases currently: None
23-Dec-2023 16:31:32 - INFO :: mylar.validateAndCreateDirectory.1857 : mass-refresh : [DIRECTORY-CHECK] Found comic directory: /comics/Timely Comics/Tex Morgan (Timely, 1948-1950)
23-Dec-2023 16:31:33 - INFO :: mylar.scale_image.75 : CP Server Thread-9 : converted to webp...
23-Dec-2023 16:31:34 - ERROR :: mylar.get_imprint_volume_and_booktype.1247 : mass-refresh : error: 'NoneType' object has no attribute 'items'
23-Dec-2023 16:31:34 - INFO :: mylar.get_imprint_volume_and_booktype.1417 : mass-refresh : comic_values: {'ComicYear': '1948', 'ComicPublisher': 'Marvel', 'PublisherImprint': None, 'ComicDescription': 'Tex Morgan ran during 1948 through 1950 for 9 issues. ', 'ComicVersion': 'None', 'Type': 'Print', 'incorrect_volume': None}
23-Dec-2023 16:31:34 - INFO :: mylar.addComictoDB.166 : mass-refresh : Now adding/updating: Tex Morgan
23-Dec-2023 16:31:34 - INFO :: mylar.addComictoDB.223 : mass-refresh : Sucessfully retrieved details for Tex Morgan
23-Dec-2023 16:31:34 - INFO :: mylar.addComictoDB.234 : mass-refresh : Previous version detected as None - seeing if update required
23-Dec-2023 16:31:34 - INFO :: mylar.addComictoDB.298 : mass-refresh : Directory (/comics/Timely Comics/Tex Morgan (Timely, 1948-1950)) already exists! Continuing...
23-Dec-2023 16:31:36 - INFO :: mylar.getImage.4143 : mass-refresh : Attempting to retrieve the comic image for series
23-Dec-2023 16:31:37 - ERROR :: mylar.excepthook.315 : mass-refresh : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/importer.py", line 326, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/helpers.py", line 4161, in getImage
    with open(coverfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/mylar/cache/30585.jpg'

Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/updater.py", line 53, in addvialist
    dbUpdate([item['comicid']], calledfrom='refresh')
  File "/app/mylar3/mylar/updater.py", line 463, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/importer.py", line 326, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/helpers.py", line 4161, in getImage
    with open(coverfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/config/mylar/cache/30585.jpg'
23-Dec-2023 16:36:32 - WARNING :: mylar.havetotals.1529 : CP Server Thread-3 : [Error: expected string or bytes-like object, got 'NoneType'] No Publisher found for Tex Morgan - you probably want to Refresh the series when you get a chance.
```

**Comment by ysarkain** [comment]
Update: I tried rolling back to ls127 and ls125, the issue continues.  Refreshing any comic causes the error, and now no cover images are showing.

**Comment by ysarkain** [comment]
It appears to have been a permission issue on the cache directory itself, it was set to 666 (drw-rw-rw-), noticed other dirs were set to 755 (drwxr-xr-x).  I did a chmod on the folder and now its working again.
